# Generated by Django 3.1 on 2024-02-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nikki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nikki',
            },
        ),
    ]
